export const nickname = "haru";
const introduction = "this is introduction";
const profileImage =
  "https://image.ohou.se/i/bucketplace-v2-development/uploads/users/profile_images/164828583192711890.jpeg?gif=1&w=72&h=72&c=c&webp=1s";
const contentImage =
  "https://image.ohou.se/i/bucketplace-v2-development/uploads/cards/snapshots/168992315568603407.jpeg?w=1440";
export const imageUrl =
  "https://image.ohou.se/i/bucketplace-v2-development/uploads/cards/projects/168520168083082625.jpg?w=1700&h=1019.5985832349469&c=c";

export const bannerUrl =
  "https://image.ohou.se/i/bucketplace-v2-development/uploads/banners/home_banner/168793929268615326.png?w=720";

export const backendData = {
  main: [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
};

export const DummyData = [
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
];
