export const nickname = "haru";
const introduction = "this is introduction";
const profileImage =
  "https://image.ohou.se/i/bucketplace-v2-development/uploads/users/profile_images/164828583192711890.jpeg?gif=1&w=72&h=72&c=c&webp=1s";
const contentImage =
  "https://image.ohou.se/i/bucketplace-v2-development/uploads/cards/snapshots/168992315568603407.jpeg?w=1440";
export const imageUrl =
  "https://img.freepik.com/premium-photo/wallpaper-with-dark-dramatic-gradient-colors-ai-generation_201606-3458.jpg";

export const backendData = {
  main: [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
};

export const DummyData = [
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
  [
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
    {
      profileImage: profileImage,
      nickname: "haru",
      introduction: introduction,
      contentImage: contentImage,
    },
  ],
];
